version: '3.4'

services:
  mongo:
    image: mongo:4.2
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=games
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - 27017:27017
